version: '3.8'

services:
  gymDB:
    image: postgres:15.3
    container_name: gym-db
    restart: always
    ports:
      - 5410:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data